/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (1000)[ProductKey]
      ,p.[ProductAlternateKey] AS [Product Item Code]
      -- ,[ProductSubcategoryKey]
      -- ,[WeightUnitMeasureCode]
      -- ,[SizeUnitMeasureCode]
      ,p.[EnglishProductName] AS [Product Name]
	  ,pc.ProductCategoryKey AS [Product Category]
	  ,ps.ProductSubcategoryKey AS [Sub Category]
	  ,pc.EnglishProductCategoryName AS [Product Category Name]
      ,ps.EnglishProductSubcategoryName AS [Product Subcategory Name]
	  -- ,[SpanishProductName]
      -- ,[FrenchProductName]
      -- ,[StandardCost]
      -- ,[FinishedGoodsFlag]
      ,p.[Color] AS [Product Color]
      -- ,[SafetyStockLevel]
      -- ,[ReorderPoint]
      -- ,[ListPrice]
      ,p.[Size] AS [Product Size]
      -- ,[SizeRange]
      -- ,[Weight]
      -- ,[DaysToManufacture]
      ,p.[ProductLine] AS [Product Line]
      -- ,[DealerPrice]
      -- ,[Class]
      -- ,[Style]
      ,p.[ModelName] AS [Product Model Name]
      -- ,[LargePhoto]
      ,p.[EnglishDescription] AS [Product Description]
	  
      -- ,[FrenchDescription]
      -- ,[ChineseDescription]
      -- ,[ArabicDescription]
      -- ,[HebrewDescription]
      -- ,[ThaiDescription]
      -- ,[GermanDescription]
      -- ,[JapaneseDescription]
      -- ,[TurkishDescription]
      -- ,[StartDate]
      -- ,[EndDate]
      ,ISNULL (p.[Status], 'OUTDATED') AS [Product Status]
  FROM [dbo].[DimProduct] AS p
  LEFT JOIN dbo.DimProductSubcategory AS ps ON ps.ProductSubcategoryKey = p.ProductSubcategoryKey
  LEFT JOIN dbo.DimProductCategory AS pc ON pc.ProductCategoryKey = ps.ProductCategoryKey
  ORDER BY p.ProductKey ASC